# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjHR33GN4EHAKW3446TKDtf1AUFDM5wf
"""

"""Loss package exports for Assignment-2 skeleton."""

from .iou_loss import IoULoss

__all__ = ["IoULoss"]